# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.BooleanField(default=False, verbose_name='是否为学员')),
                ('checked', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('raw_string', models.TextField(blank=True, null=True, verbose_name='指纹仪模板')),
            ],
        ),
        migrations.CreateModel(
            name='AttentionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.CharField(choices=[('1', '白班'), ('2', '夜班')], max_length=1)),
                ('lock', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
                ('person', models.ManyToManyField(to='worker.AttentionDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal', models.CharField(max_length=513, verbose_name='指纹模型')),
                ('weight', models.PositiveSmallIntegerField(null=True, verbose_name='习惯权重')),
                ('name', models.CharField(choices=[('左手大拇指', '左手大拇指'), ('左手食指', '左手食指'), ('左手中指', '左手中指'), ('左手无名指', '左手无名指'), ('左手小拇指', '左手小拇指'), ('右手大拇指', '右手大拇指'), ('右手食指', '右手食指'), ('右手中指', '右手中指'), ('右手无名指', '右手无名指'), ('右手小拇指', '右手小拇指')], max_length=5)),
            ],
            options={
                'ordering': ('weight',),
            },
        ),
        migrations.CreateModel(
            name='FigureSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('number', models.PositiveSmallIntegerField(verbose_name='定员数')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='姓名')),
                ('is_study', models.BooleanField(default=False)),
                ('class_number', models.PositiveSmallIntegerField(blank=True, choices=[(0, '替班'), (1, '一班'), (2, '二班'), (3, '三班'), (4, '四班')], null=True)),
                ('figures', models.ManyToManyField(blank=True, editable=False, to='worker.Figure', verbose_name='指纹库')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Position')),
            ],
        ),
        migrations.AddField(
            model_name='attentiondetail',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Position'),
        ),
        migrations.AddField(
            model_name='attentiondetail',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set([('name', 'department')]),
        ),
        migrations.AlterUniqueTogether(
            name='attentiontable',
            unique_together=set([('department', 'date', 'day_number')]),
        ),
    ]
