# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPlanBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassPlanDayDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField()),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_plan.ClassPlanBase')),
            ],
        ),
        migrations.CreateModel(
            name='ClassPlanDayTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateField()),
                ('publish_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SingleClaimDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('number', models.PositiveSmallIntegerField()),
                ('claim_time', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
            ],
        ),
        migrations.CreateModel(
            name='SinglePublishDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=500)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_detail', to='class_plan.ClassPlanDayDetail')),
            ],
        ),
        migrations.CreateModel(
            name='WhichDepartmentCanEditClassPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
            ],
        ),
        migrations.AddField(
            model_name='singleclaimdetail',
            name='father_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_plan.SinglePublishDetail'),
        ),
        migrations.AddField(
            model_name='classplandaydetail',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_detail', to='class_plan.ClassPlanDayTable'),
        ),
    ]
