# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('call_over', '0001_initial'),
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('checked_by_first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accident_first', to='call_over.CallOverDetail')),
                ('checked_by_forth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accident_forth', to='call_over.CallOverDetail')),
                ('checked_by_second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accident_second', to='call_over.CallOverDetail')),
                ('checked_by_third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accident_third', to='call_over.CallOverDetail')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='附件')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='accident',
            name='files',
            field=models.ManyToManyField(to='accidentCase.AccidentFiles', verbose_name='相关文件'),
        ),
        migrations.AddField(
            model_name='accident',
            name='publish_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
